---
abstract: 'C<lib> that makes relative path absolute to caller.'
author:
  - '-2020 by Mons Anderson.'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  inc::Module::Install: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: lib-abs
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  lib::abs:
    file: lib/lib/abs.pm
    version: '0.95'
requires:
  Cwd: '3.12'
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/Mons/lib-abs
version: '0.95'
